set runtimepath+=~/vim,~/vim/after,~/vim/pack
set packpath+=~/vim/pack
set viminfo+=n~/vim/viminfo

" Search
set incsearch " Enable incremental search
set hlsearch " Highlight results while searching
set ignorecase " Search in case-insensitive mode
set smartcase " Searches become case-sensitive when typing upper-case letters

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

hi Search ctermbg=10
