alias l="ls -CF"
alias bim=vim
alias reload=". ~/.bashrc"
alias u="cd .."
alias goenv=". ~/mud/env/bin/activate"
alias g="grep -iR"
alias log="tail -n 100 ~/mud/aelandris/server/logs/server.log"
alias runtests="evennia test --settings settings.py tests"
alias cover="coverage run --source='.' `which evennia` test --settings=settings.py"
