alias config='/usr/bin/git --git-dir=/home/alex/.cfg/ --work-tree=/home/alex'

if [ -f ~/bash/bash_aliases ]; then
    . ~/bash/bash_aliases
fi
if [ -f ~/bash/bash_prompt ]; then
    . ~/bash/bash_prompt
fi

VIMINIT="source ~/vim/vimrc"
